### ISSUE TITLE
Application web 

### ISSUE THREAD

**Issue by honorableCon** [Dar-rius/Wolof_IA#1]
Redesigner la partie front de l'application web

**Comment by Dar-rius** [comment]
Merci de votre interet pour le projet.
Avez vous une idée de design a soumettre ?

**Comment by Dar-rius** [comment]
@honorableCon  vous avez une proposition ?

**Comment by honorableCon** [comment]
Tonight je vais voir ce que je peux proposer

**Comment by Dar-rius** [comment]
D'accord merci
