### ISSUE TITLE
Identification de la langue 

### ISSUE THREAD

**Issue by niangalla** [Dar-rius/Wolof_IA#6]
Bonjour, en faisant des tests j’ai remarqué qu’il manque une vérification de la langue de saisie des messages !
Ne serait il pas possible de checker si la langue du message est bien le Wolof ?

**Comment by Dar-rius** [comment]
Bonjour @niangalla, c'est possible en créant un dictionnaire de plusieurs mots en francais, pour vérifier si dans la phrase un de ces mots par exemple on va empecher l'utilisateur d'entré sa phrase ou on peut aussi utiliser une IA pour qu'il vérifie la phrase, on va y travailler
